### ISSUE TITLE
sv_cheats?

### ISSUE THREAD

**Issue by p410n3** [grayk79/knifechoose.nut#1]
Hey. 
Firstly, Thanks for making this. its very nice. I used it alot with friends.
However i tested it without using sv_cheats (or rather having it to 0) and it works just fine.
On the bananagaming site it says you need sv_cheats sooo... whats true now?

**Comment by grayk79** [comment]
Actually, I don't really know. Before on the very first release sv_cheats was required. But in the past few releases I changed the way it works, so it relies less on console commands and more on vscript functions(this also fixed some bugs). I have to check it, but not now, cause I should be sleeping already (pre-sleeping reddit anyone?). Tomorrow after the school I gotta check, and if it is true and everything works as intended, gotta update it. Thanks for the information :)

**Comment by p410n3** [comment]
Same here with the pre sleeping reddit. So i tested further and it works
great without sv_cheats. I forked this project to add some ideas as well so
we might work a bit together

**Comment by grayk79** [comment]
Great. Thanks!
