### ISSUE TITLE
Add weapon_knife_ghost from new Halloween update

### ISSUE THREAD

**Issue by sjain882** [grayk79/knifechoose.nut#4]
Please :D

Would be much appreciated as this is only supported for a short time. If it's just a matter of copy paste that's great

Many thanks in advance for this amazing script

**Comment by SergeyKasmy** [comment]
This repo is no longer active, please write [here](https://github.com/p410n3/knifechoose.nut)
(I'm the og creator, lost my two-factor auth keys, had to create a new account)

Sorry for the inconvenience

**Comment by sjain882** [comment]
I can't write anything there, there is no issues area and pull requests says nothing to compare.

I've already told you here, surely this is visible to others?

EDIT: May have appeared rude, I'm new to github, wasn't meaning to be rude

**Comment by SergeyKasmy** [comment]
Yeah, I'm still gonna take a look at what I can do, just wanted to warn you that we moved there. If everything works out nicely, there should be an update today or early tomorrow :)

**Comment by p410n3** [comment]
@sjain882 Its updated! Take a look at the fork in my account

**Comment by sjain882** [comment]
Thanks so much <3 So quick like last time. You people are pros. And thanks for the message - sorry my comment seemed rude, didn't mean anything of the sort.

**Comment by p410n3** [comment]
@sjain882 Would you close this Issue then?

**Comment by sjain882** [comment]
Sorry, new to github
